### ISSUE TITLE
Style Apps in Gmail

### ISSUE THREAD

**Issue by irenmax** [irenmax/arcy-gmail#3]
If Apps in Gmail are activated (Google Meet and Google Chat), they appear in a sidebar. The style of these apps should be aligned with the rest of Gmail. 
<img width="368" alt="image" src="https://user-images.githubusercontent.com/37368539/235355527-31f30c69-4f68-4a5a-9572-1cacb461d9b6.png">

## Tasks
- [ ] Color of app icons and their background
- [ ] Background and font color of the chat selection modal
- [ ] Color of the main Background of the Google Chat and Google Meet apps
